### ISSUE TITLE
Multifusion support

### ISSUE THREAD

**Issue by radandreicristian** [felifri/MAGBIG#2]
Hi,

Thanks for this amazing work!

In the paper you mention using MultiFusion as a baseline. I could not find the weights on HF nor any ref to it in your code. 

Was wondering if you could tell me where did you get the weights from, and how can I reproduce the results from that baseline.

Thanks!

**Comment by felifri** [comment]
The weights stem from a cooperation with AlephAlpha. They did not consider a publication of the weights so far.
